name: EclipseCore
version: ${project.version}
main: gg.eclipsemc.eclipsecore.EclipseCore
api-version: 1.17
authors: [ SimplyMerlin, Nucker ]
description: Core.
website: https://eclipsemc.gg/
depend: [PlaceholderAPI]
